services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.5
    environment:
      # 单节点模式配置
      - discovery.type=single-node
      # 内存配置
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      # 安全配置（测试环境，禁用安全认证）
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data  # 可选：数据持久化
    command: >
      bash -c "
        # 检查插件是否已安装
        if ! elasticsearch-plugin list | grep -q analysis-ik; then
          echo '🔧 安装IK插件...'
          elasticsearch-plugin install --batch https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-9.1.5.zip
          echo '✅ IK插件安装完成'
        fi
        # 启动ES
        /usr/local/bin/docker-entrypoint.sh
      "

volumes:
  es-data:
    driver: local