name: Docker Build

on:
  push:
    branches:
      - main   # 你可以改成需要触发的分支，比如 master/dev
      - dev
      - actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "flycash"
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image with Make
        run: make docker_build

      - name: Push Docker image
        run: docker push flycash/kbase:latest
